vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        articles:
            uri_prefix: /images/articles-Image
            upload_destination: '%kernel.project_dir%/public/images/articles-Image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
